/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import DTO.ClienteDTO;
import Negocio.ClienteNegocio;
import Negocio.IClienteNegocio;
import Negocio.NegocioException;
import Persistencia.ClienteDAO;
import Persistencia.ConexionBD;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author cesar
 */
public class NuevoRegistro extends javax.swing.JFrame {
private ClienteDTO cliente;
private IClienteNegocio clienteNegocio;
    /**
     * Creates new form NuevoRegistro
     */
    public NuevoRegistro() {
        initComponents();
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.cliente=null;
    }
     public NuevoRegistro(ClienteDTO cliente) {
        initComponents();
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.cliente=cliente;
    if (cliente != null) {
            jTextField1.setText(cliente.getNombre());
            jTextField2.setText(cliente.getApellidoP());
            jTextField3.setText(cliente.getApellidoM());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblApellidoP = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        lblApellidoM = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        lblCamposObligatorios = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setText("Nuevo registro de cliente");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 20));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("Nombres*");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 270, -1));

        lblApellidoP.setText("Apellido Paterno*");
        jPanel1.add(lblApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 270, -1));

        lblApellidoM.setText("Apellido Materno*");
        jPanel1.add(lblApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 270, -1));

        lblCamposObligatorios.setText("* Campos Obligatorios");
        jPanel1.add(lblCamposObligatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       String nombre = jTextField1.getText();
    String apellidoP = jTextField2.getText();
    String apellidoM = jTextField3.getText();
    
    
        
     if (cliente == null) {
            // Es un nuevo cliente, llamamos a la capa de negocio para agregarlo
            ClienteDTO nuevoCliente = new ClienteDTO();
            nuevoCliente.setNombre(nombre);
            nuevoCliente.setApellidoP(apellidoP);
            nuevoCliente.setApellidoM(apellidoM);

            // Llamar a la capa de negocio para guardar el nuevo cliente
            guardarNuevoCliente(nuevoCliente);
        } else {
            // Es una edición, actualizamos el cliente existente
            cliente.setNombre(nombre);
            cliente.setApellidoP(apellidoP);
            cliente.setApellidoM(apellidoM);

            // Llamar a la capa de negocio para actualizar el cliente
            actualizarCliente(cliente);
        }
    }

    private void guardarNuevoCliente(ClienteDTO nuevoCliente) {
        try {
            IClienteNegocio clienteNegocio = new ClienteNegocio(new ClienteDAO(new ConexionBD()));
            clienteNegocio.guardar(nuevoCliente);
            JOptionPane.showMessageDialog(this, "Cliente guardado con éxito.");
            this.dispose(); // Cerrar la ventana después de guardar
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el cliente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void actualizarCliente(ClienteDTO cliente) {
        try {
            IClienteNegocio clienteNegocio = new ClienteNegocio(new ClienteDAO(new ConexionBD()));
            clienteNegocio.Editar(cliente);
            JOptionPane.showMessageDialog(this, "Cliente actualizado con éxito.");
            this.dispose(); // Cerrar la ventana después de actualizar
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar el cliente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    PresentacionCliente pre=new PresentacionCliente();
    pre.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblCamposObligatorios;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
